# Obtain a starting image for the Apache Web Server
FROM ubuntu:latest
ENV DEBIAN_FRONTEND=nonintercative
RUN apt-get update
RUN apt-get install vim -y
RUN apt-get install sudo -y
RUN apt-get install apache2 -y
RUN apt-get install apache2-utils

#User1
RUN sudo adduser user
RUN sudo passwd -d user
RUN sudo usermod -aG sudo user
# Set the working directory to match DocumentRoot                                   
WORKDIR /home/user/public_html
RUN sudo a2enmod 
RUN sudo a2enmod userdir
RUN sudo a2enmod autoindex
RUN sudo a2enmod rewrite
RUN sudo a2enmod alias
# Copy your index.html file to DocumentRoot directory               
COPY index.html .

WORKDIR /home/user/public_html/Dev
COPY confidential.html .

WORKDIR /home/user/public_html/Dev
COPY .htaccess .

WORKDIR /var/www/html
COPY confidential.html .
COPY .htaccess .

#Create the Directory Structure
WORKDIR /var/www/
RUN sudo mkdir -p /var/www/site1.internal/public_html
RUN sudo mkdir -p /var/www/site2.internal/public_html
RUN sudo mkdir -p /var/www/site3.internal/public_html

#Grant Permissions
RUN sudo chown -R $USER:$USER /var/www/site1.internal/public_html
RUN sudo chown -R $USER:$USER /var/www/site2.internal/public_html
RUN sudo chown -R $USER:$USER /var/www/site3.internal/public_html

RUN sudo chmod -R 755 /var/www
#Create Demo Page for Each Virtual Host 
WORKDIR /var/www/site1.internal/public_html 
COPY index.html .

WORKDIR /var/www/site2.internal/public_html 
COPY index.html .

WORKDIR /var/www/site3.internal/public_html 
COPY index.html .

WORKDIR /etc/apache2/sites-available/
COPY site1.conf .
COPY site2.conf .
COPY site3.conf . 

#Create New Virtual Host Files
RUN sudo a2ensite site1.conf 
RUN sudo a2ensite site2.conf
RUN sudo a2ensite site3.conf

RUN sudo a2dissite 000-default.conf 

#Create a Password File
RUN sudo htpasswd -c /etc/apache2/.htpasswd sammy
RUN sudo htpasswd /etc/apache2/.htpasswd another_user

# Add in other directives as needed
#LABEL Maintainer: "christianne.gargoles.439@my.csun.edu"
#EXPOSE 80
#CMD apache2ctl -D FOREGROUND
#CMD systemctl service restart apache2
#CMD sysyemctl status apache2 
#EXECs